name: ai-board
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  ui:
    build:
      context: ./
      dockerfile: ./ui/Dockerfile
    ports: 
      - 3000:3000
    depends_on:
      - db
    
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports: 
      - 3001:3001
    depends_on:
      - db
volumes:
  data:
    name: data