name: ai-board
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  ui:
    build:
      context: ./
      dockerfile: ./ui/Dockerfile
    ports: 
      - 3000:3000
    depends_on:
      - db
    environment:
        AUTH_TRUST_HOST: true
        AUTH_URL: "https://localhost/api/auth"
        NEXT_PUBLIC_URL: "https://localhost"
        DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
        PV_KEY: ""
        AUTH_SECRET: ""
        AUTH_GITHUB_ID: ""
        AUTH_GITHUB_SECRET: ""
        SMTP_HOST: ""
        SMTP_EMAIL: ""
        SMTP_PASSWORD: ""
        SMTP_PORT: ""
        SMTP_CLIENT_ID: ""
        SMTP_SECRET: ""
        SMTP_REFRESH: ""
        SMTP_ACCESS: ""
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports: 
      - 3001:3001
    depends_on:
      - db
    environment:
        AUTH_TRUST_HOST: true
        DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
        PV_KEY: ""
        AUTH_SECRET: ""
        AUTH_GITHUB_ID: ""
        AUTH_GITHUB_SECRET: ""
        SMTP_HOST: ""
        SMTP_EMAIL: ""
        SMTP_PASSWORD: ""
        SMTP_PORT: ""
        SMTP_CLIENT_ID: ""
        SMTP_SECRET: ""
        SMTP_REFRESH: ""
        SMTP_ACCESS: ""

volumes:
  data:
    name: data