name: ai-board
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: ""
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  ui:
    build:
      context: ./
      dockerfile: ./ui/Dockerfile
    ports: 
      - 3000:3000
    depends_on:
      - db
    environment:
        DATABASE_URL: ""
        PV_KEY: ""
        AUTH_SECRET: ""
        AUTH_GITHUB_ID: ""
        AUTH_GITHUB_SECRET: ""
        SMTP_HOST: ""
        SMTP_EMAIL: ""
        SMTP_PASSWORD: ""
        SMTP_PORT: ""
        SMTP_CLIENT_ID: ""
        SMTP_SECRET: ""
        SMTP_REFRESH: ""
        SMTP_ACCESS: ""
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    ports: 
      - 3001:3001
    depends_on:
      - db
    environment:
        NEXT_PUBLIC_URL: "127.0.0.1"
        DATABASE_URL: ""
        PV_KEY: ""
        AUTH_SECRET: ""
        AUTH_GITHUB_ID: ""
        AUTH_GITHUB_SECRET: ""
        SMTP_HOST: ""
        SMTP_EMAIL: ""
        SMTP_PASSWORD: ""
        SMTP_PORT: ""
        SMTP_CLIENT_ID: ""
        SMTP_SECRET: ""
        SMTP_REFRESH: ""
        SMTP_ACCESS: ""

volumes:
  data:
    name: data