name: boarder-dev
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - db
  redis:
    build:
      context: ./redis
      dockerfile: ./Dockerfile
    ports:
      - "6379:6379"
    networks:
      - redis
networks:
  db:
    name: db
  redis:
    name: redis