name: boarder-dev
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - db
  redis:
    build:
      context: ./redis
      dockerfile: ./Dockerfile
    ports:
      - "6379:6379"
    networks:
      - redis
  rest-redis:
    image: hiett/serverless-redis-http
    ports:
      - "8079:80"
    environment:
      SRH_MODE: env
      SRH_TOKEN: default
      SRH_CONNECTION_STRING: 'redis://default:password@redis:6379'
    networks:
      - redis
      - rest-redis
networks:
  db:
    name: db
  redis:
    name: redis
  rest-redis:
    name: rest-redis