name: ai-board
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  ui:
    build:
      context: ./
      dockerfile: ./ui/Dockerfile
    depends_on:
      - db
  agent:
    build:
      context: ./
      dockerfile: ./core/Dockerfile
    depends_on:
      - db
volumes:
  data:
    name: data